default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USER") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>

development:
  <<: *default
  host: localhost
  database: gatherin_development

test:
  <<: *default
  host: localhost
  database: gatherin_test

production:
  <<: *default
  database: gatherin_production
  timeout: 5000
  variables:
    statement_timeout: 5000
